# New and cleaned up verions of foslom config file
# Some parameters are changed to ensure reliable resutls on most experiments
# Any new format or data should have go to a new folder

site:
  name: Folsom

paths:
  data_dir: /home/kyber/projects/digital_energy/folsom_ds/processed2
  pv_path: irradiance
  sky_image_path: sky.zarr 
  sat_path: sat_goes_gridsat
  nwp_path: NWP

sampling:
  train_epoch_len: 50000 # number of anchors per training epoch
  csv_interval_min: 1
  pv_input_interval_min: 5
  pv_input_len: 576
  pv_output_interval_min: 15
  pv_output_len: 16
  # chronological split of data for training, validation, and testing
  train_split: 0.66 
  val_split: 0.17
  test_split: 0.17
  test_anchor_stride_min: 100
  val_anchor_stride_min: 250
  skyimg_window_size: 30
  skyimg_time_resolution_min: 1
  skyimg_spatial_size: 224
  # extra channels for sky image: ray_map, sun_mask, sky_mask
  ray_map: true  # true | false
  sun_mask: sun_only  # none | sun_only | sun_halo | gaussian_pixel | gaussian_angular
  sun_mask_sigma_px: 70
  sun_mask_sigma_deg: 55
  sky_mask: tight  # none | loose | tight | valid_disc
  satimg_window_size: 24
  satimg_time_resolution_min: 15
  satimg_npy_shape_hwc: [100, 100, 3]
  use_satellite: false

