# FusionSolar API credentials.
pv:
  endpoint: "cn.fusionsolar.huawei.com"
  username: "XINSHENG_power"
  password: "gs6300_power@123"

# JAXA ftp
jaxa_ftp:
  host: "ftp.ptree.jaxa.jp"
  user: "weize.zhang_h-partners.com"
  password: "SP+wari8"